steps:
  - label: "build-gnu-x86-remote_endpoint"
    commands:
     - cargo build --release --features=remote_endpoint
    retry:
      automatic: false
    agents:
      platform: x86_64.metal
      os: linux
    plugins:
      - docker#v3.0.1:
          image: "rustvmm/dev:v5"
          always-pull: true

  - label: "build-musl-x86-remote_endpoint"
    commands:
     - cargo build --release --features=remote_endpoint --target x86_64-unknown-linux-musl
    retry:
      automatic: false
    agents:
      platform: x86_64.metal
      os: linux
    plugins:
      - docker#v3.0.1:
          image: "rustvmm/dev:v5"
          always-pull: true

  - label: "build-gnu-arm-remote_endpoint"
    commands:
     - cargo build --release --features=remote_endpoint
    retry:
      automatic: false
    agents:
      platform: arm.metal
      os: linux
    plugins:
      - docker#v3.0.1:
          image: "rustvmm/dev:v5"
          always-pull: true

  - label: "build-musl-arm-remote_endpoint"
    commands:
     - cargo build --release --features=remote_endpoint --target aarch64-unknown-linux-musl
    retry:
      automatic: false
    agents:
      platform: arm.metal
      os: linux
    plugins:
      - docker#v3.0.1:
          image: "rustvmm/dev:v5"
          always-pull: true

  - label: "check-warnings-x86"
    commands:
      - RUSTFLAGS="-D warnings" cargo check --features=remote_endpoint
    retry:
      automatic: false
    agents:
      platform: x86_64.metal
      os: linux
    plugins:
      - docker#v3.0.1:
          privileged: true
          image: "rustvmm/dev:v5"
          always-pull: true

  - label: "check-warnings-arm"
    commands:
      - RUSTFLAGS="-D warnings" cargo check --features=remote_endpoint
    retry:
      automatic: false
    agents:
      platform: arm.metal
      os: linux
    plugins:
      - docker#v3.0.1:
          privileged: true
          image: "rustvmm/dev:v5"
          always-pull: true
